const starter=[{id:crypto.randomUUID(),term:'Meine erste Gebärde',description:'Tippe auf ⚙︎ und füge eine Beschreibung sowie ein Bild deiner Gebärde ein.',image:''}];
let cards=load(); let index=0; let showingImage=false; let editingId=null; let pendingImage=null;
function load(){try{return JSON.parse(localStorage.getItem('portaCards'))||starter}catch{return starter}}
function save(){localStorage.setItem('portaCards',JSON.stringify(cards))}
const $=id=>document.getElementById(id);
function render(){if(!cards.length){cards=starter;save()} index=Math.max(0,Math.min(index,cards.length-1)); const c=cards[index]; $('term').textContent=c.term; $('termBack').textContent=c.term; $('description').textContent=c.description; $('counter').textContent=`${index+1} / ${cards.length}`; $('progressBar').style.width=`${((index+1)/cards.length)*100}%`; $('front').classList.toggle('hidden',showingImage); $('back').classList.toggle('hidden',!showingImage); if(c.image){$('signImage').src=c.image;$('signImage').classList.remove('hidden');$('noImage').classList.add('hidden')}else{$('signImage').removeAttribute('src');$('signImage').classList.add('hidden');$('noImage').classList.remove('hidden')}}
function next(){index=(index+1)%cards.length;showingImage=false;render()} function prev(){index=(index-1+cards.length)%cards.length;showingImage=false;render()}
$('card').addEventListener('click',()=>{if(!showingImage){showingImage=true;render()}else next()}); $('card').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('card').click()}}); $('nextBtn').onclick=e=>{e.stopPropagation();next()}; $('prevBtn').onclick=e=>{e.stopPropagation();prev()}; $('shuffleBtn').onclick=e=>{e.stopPropagation();cards=cards.sort(()=>Math.random()-.5);index=0;showingImage=false;save();render()};
$('settingsBtn').onclick=()=>{renderList();$('editor').showModal()};
function renderList(){$('list').innerHTML='';cards.forEach(c=>{const row=document.createElement('div');row.className='listItem';const img=document.createElement('img');img.className='thumb';if(c.image)img.src=c.image;const txt=document.createElement('div');txt.className='listText';txt.innerHTML=`<b>${escapeHtml(c.term||'Ohne Titel')}</b><span>${escapeHtml(c.description||'Keine Beschreibung')}</span>`;const b=document.createElement('button');b.type='button';b.className='editMini';b.textContent='Bearbeiten';b.onclick=()=>openEdit(c.id);row.append(img,txt,b);$('list').append(row)})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
$('addBtn').onclick=()=>{const c={id:crypto.randomUUID(),term:'Neue Gebärde',description:'Beschreibung eintragen',image:''};cards.push(c);save();renderList();openEdit(c.id)};
function openEdit(id){editingId=id;pendingImage=null;const c=cards.find(x=>x.id===id);$('editTerm').value=c.term;$('editDescription').value=c.description;if(c.image){$('preview').src=c.image;$('preview').classList.remove('hidden')}else{$('preview').classList.add('hidden');$('preview').removeAttribute('src')}$('editCardDialog').showModal()}
$('editImage').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingImage=r.result;$('preview').src=pendingImage;$('preview').classList.remove('hidden')};r.readAsDataURL(f)});
$('saveBtn').onclick=()=>{const c=cards.find(x=>x.id===editingId);c.term=$('editTerm').value.trim()||'Ohne Titel';c.description=$('editDescription').value.trim()||'Keine Beschreibung';if(pendingImage)c.image=pendingImage;save();renderList();render();$('editCardDialog').close();$('editImage').value=''};
$('deleteBtn').onclick=()=>{if(cards.length===1){alert('Mindestens eine Karte muss vorhanden sein.');return}cards=cards.filter(x=>x.id!==editingId);index=0;save();renderList();render();$('editCardDialog').close()};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();
